### ISSUE TITLE
NoClassDefFoundError repackaged/com/arakelian/docker/junit/org/apache/commons/codec/binary/Base64

### ISSUE THREAD

**Issue by alanmm9** [arakelian/docker-junit-rule#4]
I am getting the following error when I am using 2.2.2 version. Downgrading to 2.1.4 fixes it.

```
java.lang.NoClassDefFoundError: repackaged/com/arakelian/docker/junit/org/apache/commons/codec/binary/Base64

    at com.spotify.docker.client.DefaultDockerClient.authHeader(DefaultDockerClient.java:2854)
    at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1329)
    at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1303)
    at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1297)
    at com.arakelian.docker.junit.Container.pullImage(Container.java:527)
    at com.arakelian.docker.junit.Container.start(Container.java:287)
    at com.arakelian.docker.junit.DockerRule$StatementWithDockerRule.evaluate(DockerRule.java:75)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: repackaged.com.arakelian.docker.junit.org.apache.commons.codec.binary.Base64
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 15 more
```

**Comment by arakelian** [comment]
Will push out fix in the next day or two. Thanks for reporting.

**Comment by arakelian** [comment]
Use version 2.3.0

**Comment by flyinprogrammer** [comment]
this might be broken again ?

**Comment by micw** [comment]
Same for 3.5.0
